export const Info = [
  {
    img: require('../assets/DairyProduct.png'),
    name: 'Essentials',
    width: 40,
    height: 40,
    screen: 'CategoryScreen',
  },
  {
    img: require('../assets/doctor.png'),
    name: 'Doctors',
    width: 38,
    height: 42,
    screen: 'CategoryScreen',
  },
  {
    img: require('../assets/food.png'),
    name: 'Restaurants',
    width: 40,
    height: 40,
    screen: 'CategoryScreen',
  },
  {
    img: require('../assets/shopping.png'),
    name: 'Shopping',
    width: 40,
    height: 40,
    screen: 'CategoryScreen',
  },
  {
    img: require('../assets/hospital.png'),
    name: 'Hospitals',
    width: 38,
    height: 42,
    screen: 'CategoryScreen',
  },
  {
    img: require('../assets/education.png'),
    name: 'Education',
    width: 48,
    height: 36,
    screen: 'CategoryScreen',
  },
  {
    img: require('../assets/globe.png'),
    name: 'Travel',
    width: 40,
    height: 42,
    screen: 'CategoryScreen',
  },
  {
    img: require('../assets/pills.png'),
    name: 'Medical',
    width: 38,
    height: 43,
    screen: 'CategoryScreen',
  },
  {
    img: require('../assets/wedding.png'),
    name: 'Wedding Requisites',
    width: 40,
    height: 40,
    screen: 'CategoryScreen',
  },
  {
    img: require('../assets/beauty.png'),
    name: 'Saloon',
    width: 40,
    height: 38,
    screen: 'CategoryScreen',
  },
  {
    img: require('../assets/repair.png'),
    name: 'Repair',
    width: 40,
    height: 40,
    screen: 'CategoryScreen',
  },
  {
    img: require('../assets/more.png'),
    name: 'Show More',
    width: 40,
    height: 40,
    screen: 'CategoryScreen',
  },
];
