export const Info = [
  {
    id: 1,
    img: require('../assets/food.png'),
    category: 'resturants',
    name: 'Restaurants',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'categoryList',
  },
  {
    id: 2,
    img: require('../assets/DairyProduct.png'),
    category: 'grocery',
    name: 'Essentials',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'categoryList',
  },
  {
    id: 2,
    img: require('../assets/doctor.png'),
    category: 'medical',
    name: 'Doctors',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'categoryList',
  },
  {
    id: 4,
    img: require('../assets/shopping.png'),
    category: 'shopping',
    name: 'Shopping',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'categoryList',
  },
  {
    id: 5,
    img: require('../assets/hospital.png'),
    name: 'Hospitals',
    category: 'medical',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'categoryList',
  },
  {
    id: 6,
    img: require('../assets/education.png'),
    name: 'Education',
    category: ['education'],
    type: 'in',
    width: 70,
    height: 70,
    screen: 'categoryList',
  },
  {
    id: 7,
    img: require('../assets/globe.png'),
    category: 'travel',
    name: 'Travel',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'categoryList',
  },
  {
    id: 8,
    img: require('../assets/pills.png'),
    category: 'medical',
    name: 'Medical',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'categoryList',
  },
  {
    id: 9,
    img: require('../assets/wedding.png'),
    category: 'wedding',
    name: 'Wedding',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'categoryList',
  },
  {
    id: 10,
    img: require('../assets/beauty.png'),
    category: 'demand',
    name: 'Saloon',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'categoryList',
  },
  {
    id: 11,
    img: require('../assets/repair.png'),
    category: 'repair',
    name: 'Repair ',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'categoryList',
  },
  {
    id: 12,
    img: require('../assets/more.png'),
    category: ['more'],
    name: 'Show More',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'CategoryScreen',
  },
];

export const value = [
  {
    id: 1,
    img: require('../assets/grocery.png'),
    category: ['dailyneed', 'grocery', 'shopping'],
    name: 'Grocery',
    type: 'array-contains-any',
    screen: 'categoryList',
  },
  {
    id: 2,
    img: require('../assets/milk.png'),
    category: ['dailyneed', 'grocery', 'shopping'],
    name: 'Milk',
    type: 'array-contains-any',
    screen: 'categoryList',
  },
  {
    id: 3,
    img: require('../assets/electrician.png'),
    category: ['demand'],
    name: 'Electrician',
    type: 'array-contains-any',
    screen: 'categoryList',
  },
  {
    id: 4,
    img: require('../assets/plumber.png'),
    category: ['demand'],
    name: 'Plumber',
    type: 'array-contains-any',
    screen: 'categoryList',
  },
  {
    id: 5,
    img: require('../assets/water.png'),
    category: ['demand'],
    name: 'Water',
    type: 'array-contains-any',
    screen: 'categoryList',
  },
  {
    id: 6,
    img: require('../assets/clean.png'),
    category: ['demand'],
    name: 'Clean',
    type: 'array-contains-any',
    screen: 'categoryList',
  },
  {
    id: 7,
    img: require('../assets/laundary.png'),
    category: ['demand'],
    name: 'Laundary',
    type: 'array-contains-any',
    screen: 'categoryList',
  },
  {
    id: 8,
    img: require('../assets/foodCategory.png'),
    category: ['resturants', 'grocery'],
    name: 'Food',
    type: 'array-contains-any',
    screen: 'categoryList',
  },
];
