export const Info = [
  {
    id: 1,
    img: require('../assets/food.png'),
    category: 'resturants',
    subCategory: 'Veg Restaurants,Non-Veg Restaurants',
    name: 'Restaurants',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'categoryList',
  },
  {
    id: 2,
    img: require('../assets/DairyProduct.png'),
    category: 'dailyneed',
    name: 'DailyNeed',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'categoryList',
  },
  {
    id: 3,
    img: require('../assets/Fitness.png'),
    category: 'fitness',
    name: 'Fitness',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'categoryList',
  },
  {
    id: 4,
    img: require('../assets/shopping.png'),
    category: 'shopping',
    name: 'Shopping',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'categoryList',
  },
  {
    id: 5,
    img: require('../assets/personalcare.png'),
    category: 'personalcare',
    name: 'PersonalCare',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'categoryList',
  },
  {
    id: 6,
    img: require('../assets/education.png'),
    name: 'Education',
    category: 'education',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'categoryList',
  },
  {
    id: 7,
    img: require('../assets/globe.png'),
    category: 'travel',
    name: 'Travel',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'categoryList',
  },
  {
    id: 8,
    img: require('../assets/pills.png'),
    category: 'medical',
    name: 'Medical',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'categoryList',
  },
  {
    id: 9,
    img: require('../assets/wedding.png'),
    category: 'wedding',
    name: 'Wedding',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'categoryList',
  },
  {
    id: 10,
    img: require('../assets/generalshops.png'),
    category: 'generalshops',
    name: 'Shops',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'categoryList',
  },
  {
    id: 11,
    img: require('../assets/repair.png'),
    category: 'repair',
    name: 'Repair ',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'categoryList',
  },
  {
    id: 12,
    img: require('../assets/ondemand.png'),
    category: 'demand',
    name: 'OnDemand',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'categoryList',
  },
  {
    id: 13,
    img: require('../assets/emergency.png'),
    category: 'emergency',
    name: 'Emergency ',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'categoryList',
  },
  {
    id: 14,
    img: require('../assets/more.png'),
    category: 'emergency',
    name: 'All Shops',
    type: 'array-contains',
    width: 70,
    height: 70,
    screen: 'CategoryScreen',
  },
];

export const value = [
  {
    id: 1,
    img: require('../assets/grocery.png'),
    category: 'grocery',
    name: 'Grocery',
    type: 'array-contains',
    screen: 'categoryList',
  },
  {
    id: 2,
    img: require('../assets/milk.png'),
    category: ['dailyneed', 'grocery', 'shopping'],
    name: 'Milk',
    type: 'array-contains-any',
    screen: 'categoryList',
  },
  {
    id: 3,
    img: require('../assets/electrician.png'),
    category: ['demand'],
    name: 'Electrician',
    type: 'array-contains-any',
    screen: 'categoryList',
  },
  {
    id: 4,
    img: require('../assets/plumber.png'),
    category: ['demand'],
    name: 'Plumber',
    type: 'array-contains-any',
    screen: 'categoryList',
  },
  {
    id: 5,
    img: require('../assets/water.png'),
    category: ['demand'],
    name: 'Water',
    type: 'array-contains-any',
    screen: 'categoryList',
  },
  {
    id: 6,
    img: require('../assets/clean.png'),
    category: ['demand'],
    name: 'Clean',
    type: 'array-contains-any',
    screen: 'categoryList',
  },
  {
    id: 7,
    img: require('../assets/laundary.png'),
    category: ['demand'],
    name: 'Laundary',
    type: 'array-contains-any',
    screen: 'categoryList',
  },
  {
    id: 8,
    img: require('../assets/foodCategory.png'),
    category: ['resturants', 'grocery'],
    name: 'Food',
    type: 'array-contains-any',
    screen: 'categoryList',
  },
];
